### ISSUE TITLE
wrong listen regex?

### ISSUE THREAD

**Issue by victorcoder** [samuelkadolph/unicorn-rails#18]
I just want to force listen to only a socket file and this regex [1] only detects the `listen` command in case it has a space at the beginning in the config file.

[1] https://github.com/samuelkadolph/unicorn-rails/blob/master/lib/unicorn_rails.rb#L27

Always starting unicorn listening in port 3000 and the socket file.

Is this something made on purpose?

**Comment by agibralter** [comment]
+1 here. Why is that? It was driving me nuts. @samuelkadolph would you be open to a PR to fix that?

**Comment by agibralter** [comment]
Ah, I wasn't paying attention and missed #20

**Comment by samuelkadolph** [comment]
Fixed by #20
